<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup>
		<AssemblyName>MicroRabbit.Banking.Application</AssemblyName>
		<RootNamespace>MicroRabbit.Banking.Application</RootNamespace>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroRabbit.Banking.Domain\MicroRabbit.Banking.Domain.csproj" />
  </ItemGroup>

</Project>
